# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

estimate_bwe <- function(mat_Y, nJ, nI, nK, xmu, xsigma, x_init, betamu, betasigma, beta_init, verbose, maxit, thresh, checkfreq, threads, p, prop_ns, cx_0, dx_0, cb_0, db_0) {
    .Call('_wordbean_estimate_bwe', PACKAGE = 'wordbean', mat_Y, nJ, nI, nK, xmu, xsigma, x_init, betamu, betasigma, beta_init, verbose, maxit, thresh, checkfreq, threads, p, prop_ns, cx_0, dx_0, cb_0, db_0)
}

estimate <- function(mat_Y_r, nJ_r, nI_r, nK_r, xmu_r, xsigma_r, x_init_r, betamu_r, betasigma_r, beta_init_r, verbose_r, maxit_r, thresh_r, checkfreq_r, threads_r, p_r, prop_ns_r, cx_0_r, dx_0_r, cb_0_r, db_0_r) {
    .Call('_wordbean_estimate', PACKAGE = 'wordbean', mat_Y_r, nJ_r, nI_r, nK_r, xmu_r, xsigma_r, x_init_r, betamu_r, betasigma_r, beta_init_r, verbose_r, maxit_r, thresh_r, checkfreq_r, threads_r, p_r, prop_ns_r, cx_0_r, dx_0_r, cb_0_r, db_0_r)
}

